/**
 * @fileoverview gRPC-Web generated client stub for chat
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.12.4
// source: Chat.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as Chat_pb from './Chat_pb';


export class ChatServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorPostMessage = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/PostMessage',
    grpcWeb.MethodType.UNARY,
    Chat_pb.PostMessageRequest,
    Chat_pb.PostMessageResponse,
    (request: Chat_pb.PostMessageRequest) => {
      return request.serializeBinary();
    },
    Chat_pb.PostMessageResponse.deserializeBinary
  );

  postMessage(
    request: Chat_pb.PostMessageRequest,
    metadata: grpcWeb.Metadata | null): Promise<Chat_pb.PostMessageResponse>;

  postMessage(
    request: Chat_pb.PostMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Chat_pb.PostMessageResponse) => void): grpcWeb.ClientReadableStream<Chat_pb.PostMessageResponse>;

  postMessage(
    request: Chat_pb.PostMessageRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Chat_pb.PostMessageResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/PostMessage',
        request,
        metadata || {},
        this.methodDescriptorPostMessage,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/PostMessage',
    request,
    metadata || {},
    this.methodDescriptorPostMessage);
  }

  methodDescriptorGetMessages = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/GetMessages',
    grpcWeb.MethodType.UNARY,
    Chat_pb.GetMessagesRequest,
    Chat_pb.GetMessagesResponse,
    (request: Chat_pb.GetMessagesRequest) => {
      return request.serializeBinary();
    },
    Chat_pb.GetMessagesResponse.deserializeBinary
  );

  getMessages(
    request: Chat_pb.GetMessagesRequest,
    metadata: grpcWeb.Metadata | null): Promise<Chat_pb.GetMessagesResponse>;

  getMessages(
    request: Chat_pb.GetMessagesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: Chat_pb.GetMessagesResponse) => void): grpcWeb.ClientReadableStream<Chat_pb.GetMessagesResponse>;

  getMessages(
    request: Chat_pb.GetMessagesRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: Chat_pb.GetMessagesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/chat.ChatService/GetMessages',
        request,
        metadata || {},
        this.methodDescriptorGetMessages,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/chat.ChatService/GetMessages',
    request,
    metadata || {},
    this.methodDescriptorGetMessages);
  }

  methodDescriptorChatFeed = new grpcWeb.MethodDescriptor(
    '/chat.ChatService/ChatFeed',
    grpcWeb.MethodType.SERVER_STREAMING,
    Chat_pb.LoginRequest,
    Chat_pb.ChatPost,
    (request: Chat_pb.LoginRequest) => {
      return request.serializeBinary();
    },
    Chat_pb.ChatPost.deserializeBinary
  );

  chatFeed(
    request: Chat_pb.LoginRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<Chat_pb.ChatPost> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/chat.ChatService/ChatFeed',
      request,
      metadata || {},
      this.methodDescriptorChatFeed);
  }

}

